swagger: '2.0'
info:
  version: 1.0.0
  title: RevenueWire Email Service
  description: An email service
basePath: /v1
schemes:
  - https
  - http
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  JWTHeader:
    type: apiKey
    in: header
    name: X-Authorization-JWT
  APIKeyHeader:
    type: apiKey
    in: header
    name: X-API-KEY
security:
  - JWTHeader: []
  - APIKeyHeader: []
definitions:
  error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: string
      message:
        type: string
  response:
    type: object
    properties:
      status:
        type: boolean
      result:
        type: object
  emailType:
    type: object
    properties:
      title:
        type: string
      fid:
        type: string
      order:
        type: integer
      types:
        type: array
        items:
          $ref: '#/definitions/emailTypeTemplate'
  emailTypeTemplate:
    type: object
    properties:
      title:
        type: string
      scope:
        type: string
        enum:
          - PUBLIC
          - PRIVATE
      accountId:
        type: integer
      productId:
        type: integer
      offerId:
        type: integer
      to:
        type: object
        properties:
          name:
            type: string
          emailAddress:
            type: string
      from:
        type: object
        properties:
          name:
            type: string
          emailAddress:
            type: string
      order:
        type: integer
      description:
        type: string
      type:
        type: string
        description: Type name must be unique
        enum:
          - GENERIC
          - PRODUCT_ACTIVATION
          - SUPPORT_CONTACT_US
          - ACCOUNT_ACTIVATION
          - FORGET_PASSWORD
          - CUSTOMER_PURCHASE_LOOKUP
          - CPA_APPLIED_TO_RUN
          - BETA_FEEDBACK
          - UPDATE_EMAIL_REQUEST
      variables:
        type: array
        description: A list of variables avaiable for the type
        items:
          $ref: '#/definitions/emailTypeVariable'
  emailTypeVariable:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
  template:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: string
      name:
        type: string
      scope:
        type: string
        enum:
          - PUBLIC
          - PRIVATE
      type:
        type: string
      accountId:
        type: integer
      productId:
        type: integer
      offerId:
        type: integer
      status:
        type: string
        enum:
          - PENDING
          - ACTIVE
          - DELETED
      lastMessageSentDate:
        type: integer
      totalMessageSent:
        type: integer
      created:
        type: integer
      modified:
        type: integer
  updateTemplate:
    type: object
    properties:
      name:
        type: string
  templateContents:
    type: array
    items:
      $ref: '#/definitions/templateContent'
  templateContent:
    type: object
    required:
      - id
      - templateId
      - lang
      - subject
      - body
    properties:
      id:
        type: string
      templateId:
        type: string
      lang:
        type: string
      subject:
        type: string
      body:
        type: string
        description: HTML formatted message
      text:
        type: string
        description: Text formatted message
      created:
        type: integer
      modified:
        type: integer
  newTemplateContent:
    type: object
    required:
      - lang
      - subject
      - body
    properties:
      lang:
        type: string
      subject:
        type: string
      body:
        type: string
        description: HTML formatted message
      text:
        type: string
        description: Text formatted message
  updateTemplateContent:
    type: object
    properties:
      subject:
        type: string
      body:
        type: string
      text:
        type: string
  newTemplate:
    type: object
    required:
      - name
      - contents
    properties:
      name:
        type: string
      scope:
        type: string
        enum:
          - PUBLIC
          - PRIVATE
      type:
        type: string
      accountId:
        type: integer
      productId:
        type: integer
      offerId:
        type: integer
      contents:
        type: array
        items:
          $ref: '#/definitions/newTemplateContent'
  resource:
    type: object
    properties:
      id:
        type: string
      accountId:
        type: integer
      scope:
        type: string
        enum:
          - PUBLIC
          - PRIVATE
      lang:
        type: string
      type:
        type: string
      content:
        type: string
      created:
        type: integer
      modified:
        type: integer
  newResource:
    type: object
    required:
      - fid
      - content
    properties:
      fid:
        type: string
      lang:
        type: string
      description:
        type: string
      type:
        type: string
      content:
        type: string
      scope:
        type: string
        enum:
          - PUBLIC
          - PRIVATE
  updateResource:
    type: object
    properties:
      lang:
        type: string
      description:
        type: string
      content:
        type: string
      scope:
        type: string
        enum:
          - PUBLIC
          - PRIVATE
  mailer:
    type: object
    required:
      - emailAddress
    properties:
      name:
        type: string
      emailAddress:
        type: string
  message:
    type: object
    required:
      - templateId
      - from
      - to
      - data
    properties:
      templateId:
        type: string
      lang:
        type: string
      from:
        $ref: '#/definitions/mailer'
      to:
        type: array
        items:
          $ref: '#/definitions/mailer'
      replyTo:
        type: array
        items:
          $ref: '#/definitions/mailer'
      cc:
        type: array
        items:
          $ref: '#/definitions/mailer'
      bcc:
        type: array
        items:
          $ref: '#/definitions/mailer'
      data:
        type: object
  previewContent:
    type: object
    required:
      - subject
      - body
      - text
    properties:
      subject:
        type: string
      body:
        type: string
      text:
        type: string
      data:
        type: string
  previewResult:
    type: object
    properties:
      subject:
        type: string
      html:
        type: object
        properties:
          body:
            type: string
          size:
            description: number of bytes
            type: integer
      text:
        type: object
        properties:
          body:
            type: string
          size:
            description: number of bytes
            type: integer
paths:
  /types:
    get:
      summary: Get a list of email types and variables
      tags:
        - Emails
      operationId: getEmailTypes
      responses:
        '200':
          description: Success Response
          schema:
            type: array
            items:
              $ref: '#/definitions/emailType'
  /templates:
    get:
      tags:
        - Templates
      description: Get all templates
      operationId: getTemplates
      parameters:
        - in: query
          name: type
          type: string
        - in: query
          name: status
          type: string
        - in: query
          name: accountId
          type: integer
        - in: query
          name: productId
          type: integer
        - in: query
          name: offerId
          type: integer
        - in: query
          name: scope
          type: string
      responses:
        '200':
          description: Success Response
          schema:
            type: array
            items:
              $ref: '#/definitions/template'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/error'
    post:
      tags:
        - Templates
      description: Create a new template
      operationId: addTemplate
      parameters:
        - name: template
          in: body
          required: true
          schema:
            $ref: '#/definitions/newTemplate'
      responses:
        '200':
          description: Success Response
          schema:
            $ref: '#/definitions/template'
        default:
          description: Error Response
          schema:
            $ref: '#/definitions/error'
  '/templates/{id}':
    get:
      tags:
        - Templates
      description: Get a template
      operationId: getTemplate
      parameters:
        - in: path
          name: id
          description: Template Id
          required: true
          type: string
      responses:
        '200':
          description: Success Response
          schema:
            $ref: '#/definitions/template'
        default:
          description: Error Response
          schema:
            $ref: '#/definitions/error'
    put:
      tags:
        - Templates
      description: Update a template
      operationId: updateTemplate
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: path
          name: id
          description: Template Id
          required: true
          type: string
        - name: template
          in: body
          required: true
          schema:
            $ref: '#/definitions/updateTemplate'
      responses:
        '200':
          description: Success Response
          schema:
            $ref: '#/definitions/template'
        default:
          description: Error Response
          schema:
            $ref: '#/definitions/error'
    delete:
      tags:
        - Templates
      description: Delete a template
      operationId: deleteTemplate
      parameters:
        - in: path
          name: id
          description: Template Id
          required: true
          type: string
      responses:
        '200':
          description: Success Response
          schema:
            $ref: '#/definitions/template'
        default:
          description: Error Response
          schema:
            $ref: '#/definitions/error'
  '/templates/{id}/preview':
    post:
      summary: Get preview of the content
      operationId: previewTemplate
      tags:
        - Templates
      parameters:
        - name: id
          type: string
          in: path
          required: true
        - name: preview
          in: body
          required: true
          schema:
            $ref: '#/definitions/previewContent'
      responses:
        '200':
          description: Suucess Response
          schema:
            $ref: '#/definitions/previewResult'
  '/templates/{id}/contents':
    get:
      tags:
        - Templates
      operationId: getContents
      parameters:
        - in: path
          name: id
          description: Template Id
          required: true
          type: string
      responses:
        '200':
          description: Success Response
          schema:
            $ref: '#/definitions/templateContents'
        default:
          description: Error Response
          schema:
            $ref: '#/definitions/error'
    post:
      tags:
        - Templates
      description: Add new template content (new language)
      operationId: addNewContent
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: path
          name: id
          description: Template Id
          required: true
          type: string
        - in: body
          name: content
          required: true
          schema:
            $ref: '#/definitions/newTemplateContent'
      responses:
        '200':
          description: Success Response
          schema:
            $ref: '#/definitions/templateContent'
        default:
          description: Error Response
          schema:
            $ref: '#/definitions/error'
  '/templates/{id}/contents/{contentId}':
    get:
      tags:
        - Templates
      operationId: getContent
      parameters:
        - in: path
          name: id
          description: Template Id
          required: true
          type: string
        - in: path
          name: contentId
          description: Content Id
          required: true
          type: string
      responses:
        '200':
          description: Success Response
          schema:
            $ref: '#/definitions/templateContent'
        default:
          description: Error Response
          schema:
            $ref: '#/definitions/error'
    delete:
      tags:
        - Templates
      operationId: deleteContent
      parameters:
        - in: path
          name: id
          description: Template Id
          required: true
          type: string
        - in: path
          name: contentId
          description: Content Id
          required: true
          type: string
      responses:
        '200':
          description: Success Response
        default:
          description: Error Response
          schema:
            $ref: '#/definitions/error'
    put:
      tags:
        - Templates
      summary: Update Template Content
      operationId: updateContent
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: path
          name: id
          description: Template Id
          required: true
          type: string
        - in: path
          name: contentId
          description: Content Id
          required: true
          type: string
        - in: body
          name: content
          schema:
            $ref: '#/definitions/updateTemplateContent'
      responses:
        '200':
          description: Success Response
          schema:
            $ref: '#/definitions/templateContent'
        default:
          description: Error Response
          schema:
            $ref: '#/definitions/error'
  /emails:
    post:
      tags:
        - Emails
      summary: Sending an email directly.
      operationId: sendEmail
      parameters:
        - in: body
          name: message
          required: true
          schema:
            $ref: '#/definitions/message'
      responses:
        '200':
          description: Success Response
          schema:
            $ref: '#/definitions/response'
        default:
          description: Error Response
          schema:
            $ref: '#/definitions/error'
  /hello:
    get:
      summary: Just say hello
      operationId: hello
      tags:
        - Hello
      responses:
        '200':
          description: Success Response
          schema:
            type: object
            properties:
              hello:
                type: string
        default:
          description: Error Response
          schema:
            $ref: '#/definitions/error'
  /resources:
    get:
      tags:
        - Resources
      description: Get all resources
      operationId: getResources
      parameters:
        - in: query
          name: type
          type: string
        - in: query
          name: accountId
          type: integer
        - in: query
          name: scope
          type: string
      responses:
        '200':
          description: Success Response
          schema:
            type: array
            items:
              $ref: '#/definitions/resource'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/error'
    post:
      tags:
        - Resources
      description: Create a new resource
      operationId: addResource
      parameters:
        - name: resource
          in: body
          required: true
          schema:
            $ref: '#/definitions/newResource'
      responses:
        '200':
          description: Success Response
          schema:
            $ref: '#/definitions/resource'
        default:
          description: Error Response
          schema:
            $ref: '#/definitions/error'
  '/resources/{id}':
    get:
      tags:
        - Resources
      description: Get a resource
      operationId: getResource
      parameters:
        - in: path
          name: id
          description: Resource Id
          required: true
          type: string
      responses:
        '200':
          description: Success Response
          schema:
            $ref: '#/definitions/resource'
        default:
          description: Error Response
          schema:
            $ref: '#/definitions/error'
    put:
      tags:
        - Resources
      description: Update a resource
      operationId: updateResource
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: path
          name: id
          description: Resource Id
          required: true
          type: string
        - name: resource
          in: body
          required: true
          schema:
            $ref: '#/definitions/updateResource'
      responses:
        '200':
          description: Success Response
          schema:
            $ref: '#/definitions/resource'
        default:
          description: Error Response
          schema:
            $ref: '#/definitions/error'
    delete:
      tags:
        - Resources
      description: Delete a resource
      operationId: deleteResource
      parameters:
        - in: path
          name: id
          description: Resource Id
          required: true
          type: string
      responses:
        '200':
          description: Success Response
          schema:
            $ref: '#/definitions/resource'
        default:
          description: Error Response
          schema:
            $ref: '#/definitions/error'
  /resources/upload:
    post:
      tags:
        - Resources
      description: Upload image resource
      consumes:
        - multipart/form-data
        - application/x-www-form-urlencoded
      parameters:
        - in: formData
          name: fid
          required: true
          type: string
        - in: formData
          name: description
          type: string
        - name: image
          in: formData
          description: image
          type: file
          required: true
        - in: formData
          name: scope
          type: string
          enum:
            - PUBLIC
            - PRIVATE
      responses:
        '200':
          description: Successful responses
          schema:
            $ref: '#/definitions/resource'
        default:
          description: Error Response
          schema:
            $ref: '#/definitions/error'
